spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888  # Fetch from Config Server

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
        - id: notes-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/notes/**
        - id: task-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/tasks/**

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: mysecretkey
  expiration: 3600000
