spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://localhost:5432/notificationdb
    username: postgres
    password: 2828
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true

# Kafka Configuration (if using Kafka)
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
