spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1  # This removes "/user-service" before forwarding

        - id: notes-service
          uri: http://localhost:8082
          predicates:
            - Path=/notes-service/**

        - id: task-service
          uri: http://localhost:8083
          predicates:
            - Path=/task-service/**

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/